import { Ingredient } from './types';

export const ingredients: Ingredient[] = [
  { id: 'tomate', name: 'Tomate', category: 'produce' },
  { id: 'cebola', name: 'Cebola', category: 'produce' },
  { id: 'alho', name: 'Alho', category: 'produce' },
  { id: 'batata', name: 'Batata', category: 'produce' },
  { id: 'batata-doce', name: 'Batata-doce', category: 'produce' },
  { id: 'cenoura', name: 'Cenoura', category: 'produce' },
  { id: 'mandioca', name: 'Mandioca', category: 'produce' },
  { id: 'abobrinha', name: 'Abobrinha', category: 'produce' },
  { id: 'abobora', name: 'Abóbora', category: 'produce' },
  { id: 'chuchu', name: 'Chuchu', category: 'produce' },
  { id: 'beterraba', name: 'Beterraba', category: 'produce' },
  { id: 'pimentao', name: 'Pimentão', category: 'produce' },
  { id: 'pepino', name: 'Pepino', category: 'produce' },
  { id: 'alface', name: 'Alface', category: 'produce' },
  { id: 'couve', name: 'Couve', category: 'produce' },
  { id: 'repolho', name: 'Repolho', category: 'produce' },
  { id: 'brocolis', name: 'Brócolis', category: 'produce' },
  { id: 'couve-flor', name: 'Couve-flor', category: 'produce' },
  { id: 'espinafre', name: 'Espinafre', category: 'produce' },
  { id: 'rucula', name: 'Rúcula', category: 'produce' },
  { id: 'quiabo', name: 'Quiabo', category: 'produce' },
  { id: 'berinjela', name: 'Berinjela', category: 'produce' },
  { id: 'milho-verde', name: 'Milho-verde', category: 'produce' },
  { id: 'gengibre', name: 'Gengibre', category: 'produce' },
  { id: 'limao', name: 'Limão', category: 'produce' },
  { id: 'laranja', name: 'Laranja', category: 'produce' },
  { id: 'banana', name: 'Banana', category: 'produce' },
  { id: 'maca', name: 'Maçã', category: 'produce' },
  { id: 'mamao', name: 'Mamão', category: 'produce' },
  { id: 'abacaxi', name: 'Abacaxi', category: 'produce' },
  { id: 'maracuja', name: 'Maracujá', category: 'produce' },
  { id: 'coco', name: 'Coco', category: 'produce' },
  { id: 'peito-de-frango', name: 'Peito de frango', category: 'protein' },
  { id: 'coxa-de-frango', name: 'Coxa de frango', category: 'protein' },
  { id: 'frango-inteiro', name: 'Frango inteiro', category: 'protein' },
  { id: 'carne-moida', name: 'Carne moída', category: 'protein' },
  { id: 'patinho', name: 'Patinho', category: 'protein' },
  { id: 'acem', name: 'Acém', category: 'protein' },
  { id: 'alcatra', name: 'Alcatra', category: 'protein' },
  { id: 'costela-bovina', name: 'Costela bovina', category: 'protein' },
  { id: 'bisteca-suina', name: 'Bisteca suína', category: 'protein' },
  { id: 'lombo-suino', name: 'Lombo suíno', category: 'protein' },
  { id: 'carne-seca', name: 'Carne seca', category: 'protein' },
  { id: 'linguica', name: 'Linguiça', category: 'protein' },
  { id: 'bacon', name: 'Bacon', category: 'protein' },
  { id: 'salsicha', name: 'Salsicha', category: 'protein' },
  { id: 'presunto', name: 'Presunto', category: 'protein' },
  { id: 'mortadela', name: 'Mortadela', category: 'protein' },
  { id: 'tilapia', name: 'Tilápia', category: 'protein' },
  { id: 'sardinha', name: 'Sardinha', category: 'protein' },
  { id: 'camarao', name: 'Camarão', category: 'protein' },
  { id: 'arroz-branco', name: 'Arroz branco', category: 'grains' },
  { id: 'arroz-integral', name: 'Arroz integral', category: 'grains' },
  { id: 'feijao-carioca', name: 'Feijão carioca', category: 'grains' },
  { id: 'feijao-preto', name: 'Feijão preto', category: 'grains' },
  { id: 'lentilha', name: 'Lentilha', category: 'grains' },
  { id: 'grao-de-bico', name: 'Grão-de-bico', category: 'grains' },
  { id: 'macarrao-espaguete', name: 'Macarrão espaguete', category: 'grains' },
  { id: 'macarrao-parafuso', name: 'Macarrão parafuso', category: 'grains' },
  { id: 'macarrao-instantaneo', name: 'Macarrão instantâneo', category: 'grains' },
  { id: 'farinha-de-trigo', name: 'Farinha de trigo', category: 'grains' },
  { id: 'farinha-de-mandioca', name: 'Farinha de mandioca', category: 'grains' },
  { id: 'fuba', name: 'Fubá', category: 'grains' },
  { id: 'aveia', name: 'Aveia', category: 'grains' },
  { id: 'goma-de-tapioca', name: 'Goma de tapioca', category: 'grains' },
  { id: 'quinoa', name: 'Quinoa', category: 'grains' },
  { id: 'milho-de-pipoca', name: 'Milho de pipoca', category: 'grains' },
  { id: 'ovo', name: 'Ovo', category: 'dairy' },
  { id: 'leite', name: 'Leite', category: 'dairy' },
  { id: 'manteiga', name: 'Manteiga', category: 'dairy' },
  { id: 'margarina', name: 'Margarina', category: 'dairy' },
  { id: 'queijo-mussarela', name: 'Queijo mussarela', category: 'dairy' },
  { id: 'queijo-prato', name: 'Queijo prato', category: 'dairy' },
  { id: 'queijo-parmesao', name: 'Queijo parmesão', category: 'dairy' },
  { id: 'queijo-minas', name: 'Queijo minas', category: 'dairy' },
  { id: 'requeijao', name: 'Requeijão', category: 'dairy' },
  { id: 'creme-de-leite', name: 'Creme de leite', category: 'dairy' },
  { id: 'leite-condensado', name: 'Leite condensado', category: 'dairy' },
  { id: 'iogurte-natural', name: 'Iogurte natural', category: 'dairy' },
  { id: 'sal', name: 'Sal', category: 'seasonings' },
  { id: 'acucar', name: 'Açúcar', category: 'seasonings' },
  { id: 'oleo-de-soja', name: 'Óleo de soja', category: 'seasonings' },
  { id: 'azeite', name: 'Azeite', category: 'seasonings' },
  { id: 'vinagre', name: 'Vinagre', category: 'seasonings' },
  { id: 'pimenta-do-reino', name: 'Pimenta-do-reino', category: 'seasonings' },
  { id: 'colorau', name: 'Colorau', category: 'seasonings' },
  { id: 'cominho', name: 'Cominho', category: 'seasonings' },
  { id: 'oregano', name: 'Orégano', category: 'seasonings' },
  { id: 'manjericao', name: 'Manjericão', category: 'seasonings' },
  { id: 'salsinha', name: 'Salsinha', category: 'seasonings' },
  { id: 'cebolinha', name: 'Cebolinha', category: 'seasonings' },
  { id: 'coentro', name: 'Coentro', category: 'seasonings' },
  { id: 'louro', name: 'Louro', category: 'seasonings' },
  { id: 'alecrim', name: 'Alecrim', category: 'seasonings' },
  { id: 'canela-em-po', name: 'Canela em pó', category: 'seasonings' },
  { id: 'cravo', name: 'Cravo', category: 'seasonings' },
  { id: 'caldo-de-galinha', name: 'Caldo de galinha', category: 'seasonings' },
  { id: 'molho-de-soja', name: 'Molho de soja', category: 'seasonings' },
  { id: 'maionese', name: 'Maionese', category: 'seasonings' },
  { id: 'ketchup', name: 'Ketchup', category: 'seasonings' },
  { id: 'mostarda', name: 'Mostarda', category: 'seasonings' },
  { id: 'milho-enlatado', name: 'Milho enlatado', category: 'canned' },
  { id: 'ervilha-enlatada', name: 'Ervilha enlatada', category: 'canned' },
  { id: 'atum-enlatado', name: 'Atum enlatado', category: 'canned' },
  { id: 'sardinha-enlatada', name: 'Sardinha enlatada', category: 'canned' },
  { id: 'extrato-de-tomate', name: 'Extrato de tomate', category: 'canned' },
  { id: 'molho-de-tomate', name: 'Molho de tomate', category: 'canned' },
  { id: 'azeitona', name: 'Azeitona', category: 'canned' },
  { id: 'palmito', name: 'Palmito', category: 'canned' },
  { id: 'leite-de-coco', name: 'Leite de coco', category: 'canned' },
  { id: 'seleta-de-legumes', name: 'Seleta de legumes', category: 'canned' },
  { id: 'pao-frances', name: 'Pão francês', category: 'bakery' },
  { id: 'pao-de-forma', name: 'Pão de forma', category: 'bakery' },
  { id: 'pao-integral', name: 'Pão integral', category: 'bakery' },
  { id: 'biscoito-cream-cracker', name: 'Biscoito cream cracker', category: 'bakery' },
  { id: 'torrada', name: 'Torrada', category: 'bakery' },
  { id: 'fermento-biologico', name: 'Fermento biológico', category: 'bakery' },
  { id: 'fermento-em-po', name: 'Fermento em pó', category: 'bakery' },
  { id: 'massa-de-pastel', name: 'Massa de pastel', category: 'bakery' },
  { id: 'cafe', name: 'Café', category: 'beverages' },
  { id: 'cha-mate', name: 'Chá mate', category: 'beverages' },
  { id: 'achocolatado-em-po', name: 'Achocolatado em pó', category: 'beverages' },
  { id: 'refrigerante', name: 'Refrigerante', category: 'beverages' },
  { id: 'suco-de-uva', name: 'Suco de uva', category: 'beverages' },
  { id: 'agua-com-gas', name: 'Água com gás', category: 'beverages' },
  { id: 'agua-de-coco', name: 'Água de coco', category: 'beverages' },
];
