sonar.projectKey=GenilsonJrs_cozinha-pratica-app
sonar.organization=genilsonjrs
sonar.projectName=cozinha-pratica-app

sonar.sources=src
sonar.exclusions=src/__tests__/**
sonar.tests=src/__tests__
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/app/_layout.tsx,src/app/(tabs)/_layout.tsx,src/features/pantry/catalog.ts
