import { Recipe } from './types';

export const recipes: Recipe[] = [
  {
    id: 'arroz-branco-soltinho',
    name: 'Arroz branco soltinho',
    minutes: 25,
    servings: 4,
    difficulty: 'facil',
    ingredients: [
      { id: 'arroz-branco', measure: '2 xícaras' },
      { id: 'alho', measure: '2 dentes picados' },
      { id: 'oleo-de-soja', measure: '2 colheres de sopa' },
      { id: 'sal', measure: '1 colher de chá' },
    ],
    steps: [
      'Lave o arroz em água corrente até a água sair quase limpa e escorra bem.',
      'Aqueça o óleo em uma panela e refogue o alho até dourar levemente, sem queimar.',
      'Junte o arroz escorrido e refogue por um minuto, mexendo para envolver os grãos.',
      'Acrescente quatro xícaras de água fervente e o sal, e misture uma única vez.',
      'Cozinhe em fogo médio sem tampar até a água chegar ao nível do arroz.',
      'Abaixe o fogo, tampe e deixe por dez minutos. Solte com um garfo antes de servir.',
    ],
  },
  {
    id: 'feijao-carioca-temperado',
    name: 'Feijão carioca temperado',
    minutes: 60,
    servings: 6,
    difficulty: 'facil',
    ingredients: [
      { id: 'feijao-carioca', measure: '2 xícaras' },
      { id: 'cebola', measure: '1 unidade picada' },
      { id: 'alho', measure: '3 dentes amassados' },
      { id: 'oleo-de-soja', measure: '2 colheres de sopa' },
      { id: 'sal', measure: 'a gosto' },
    ],
    steps: [
      'Deixe o feijão de molho em água por pelo menos quatro horas e descarte essa água.',
      'Cozinhe o feijão na pressão com água suficiente para cobrir dois dedos acima dos grãos.',
      'Conte vinte e cinco minutos após a panela pegar pressão e desligue.',
      'Em outra panela, refogue a cebola no óleo até ficar transparente e junte o alho.',
      'Transfira duas conchas de feijão com caldo para o refogado e amasse com a colher.',
      'Devolva tudo à panela do feijão, tempere com sal e cozinhe por mais dez minutos.',
    ],
  },
  {
    id: 'cafe-coado',
    name: 'Café coado',
    minutes: 10,
    servings: 4,
    difficulty: 'facil',
    ingredients: [
      { id: 'cafe', measure: '4 colheres de sopa' },
      { id: 'acucar', measure: 'a gosto' },
    ],
    steps: [
      'Ferva meio litro de água e espere baixar a fervura por cerca de um minuto.',
      'Escalde o coador com um pouco da água quente e descarte essa água.',
      'Coloque o pó no coador e despeje a água aos poucos, em movimentos circulares.',
      'Adoce ainda quente, se preferir, e sirva em seguida.',
    ],
  },
  {
    id: 'ovo-frito',
    name: 'Ovo frito',
    minutes: 5,
    servings: 1,
    difficulty: 'facil',
    ingredients: [
      { id: 'ovo', measure: '2 unidades' },
      { id: 'oleo-de-soja', measure: '1 colher de sopa' },
      { id: 'sal', measure: 'a gosto' },
    ],
    steps: [
      'Aqueça o óleo em uma frigideira pequena em fogo médio.',
      'Quebre os ovos com cuidado para não romper as gemas.',
      'Tempere com sal e frite até a clara firmar e as bordas ficarem douradas.',
      'Para gema mole, tampe a frigideira por trinta segundos e desligue.',
    ],
  },
  {
    id: 'macarrao-alho-e-oleo',
    name: 'Macarrão alho e óleo',
    minutes: 20,
    servings: 2,
    difficulty: 'facil',
    ingredients: [
      { id: 'macarrao-espaguete', measure: '250 gramas' },
      { id: 'alho', measure: '5 dentes fatiados' },
      { id: 'azeite', measure: '4 colheres de sopa' },
      { id: 'salsinha', measure: '2 colheres de sopa picada' },
      { id: 'sal', measure: 'a gosto' },
    ],
    steps: [
      'Cozinhe o macarrão em água fervente com sal até ficar al dente.',
      'Separe meia xícara da água do cozimento antes de escorrer.',
      'Aqueça o azeite em fogo baixo e doure o alho devagar, até ficar levemente dourado.',
      'Junte o macarrão escorrido e a água reservada, mexendo para formar um molho leve.',
      'Finalize com a salsinha, acerte o sal e sirva imediatamente.',
    ],
  },
  {
    id: 'omelete-de-queijo',
    name: 'Omelete de queijo',
    minutes: 10,
    servings: 1,
    difficulty: 'facil',
    ingredients: [
      { id: 'ovo', measure: '3 unidades' },
      { id: 'queijo-mussarela', measure: '50 gramas ralado' },
      { id: 'manteiga', measure: '1 colher de sopa' },
      { id: 'cebolinha', measure: '1 colher de sopa picada' },
      { id: 'sal', measure: 'a gosto' },
    ],
    steps: [
      'Bata os ovos com o sal até a mistura ficar homogênea e levemente aerada.',
      'Derreta a manteiga em uma frigideira antiaderente em fogo médio-baixo.',
      'Despeje os ovos e cozinhe sem mexer até as bordas começarem a firmar.',
      'Espalhe o queijo e a cebolinha sobre uma das metades.',
      'Dobre a omelete ao meio e cozinhe por mais um minuto, até o queijo derreter.',
    ],
  },
];
